name: Compilar IPA

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Seleccionar version de Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Compilar Proyecto (.app)
        run: |
          xcodebuild build \
            -project ThreeOneOSFive.xcodeproj \
            -scheme 3105 \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Empaquetar en archivo .IPA
        run: |
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r 3105.ipa Payload

      - name: Subir ejecutable IPA
        uses: actions/upload-artifact@v4
        with:
          name: App-IPA
          path: 3105.ipa
